version: '3.4'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Keep configs, scrapers, and plugins here.
      - /youtube-dl/config:/root/.stash
      ## Point this at your collection.
      - /youtube-dl/videos:/data
      ## This is where your stash's metadata lives
      - /youtube-dl/metadata:/metadata
      ## Any other cache content.
      - /youtube-dl/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /youtube-dl/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /youtube-dl/generated:/generated