version: '3.4'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ports:
      - "9999:9999"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /docker/data/stash:/data
      - ./config:/root/.stash
      - ./metadata:/metadata
      - ./cache:/cache
      - ./blobs:/blobs
      - ./generated:/generated

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    ports:
      - '9091:9091'
    cap_add:
      - NET_ADMIN
    volumes:
      - /docker/conf/transmission-openvpn:/data
      - /docker/data/stash/downloads:/downloads
    environment:
      - TZ=Europe/Stockholm
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${NORDVPN_USER}
      - OPENVPN_PASSWORD=${NORDVPN_PASS}
      - NORDVPN_COUNTRY=SI
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=tcp
      - LOCAL_NETWORK=10.0.0.0/16
      - TRANSMISSION_WEB_UI=combustion
      - TRANSMISSION_PREALLOCATION=1
      - TRANSMISSION_RATIO_LIMIT=2
      - TRANSMISSION_RATIO_LIMIT_ENABLED=True
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=200
      - TRANSMISSION_DOWNLOAD_DIR=/downloads/complete
      - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
    restart: unless-stopped