services:
  git-checkout:
    container_name: git-checkout-youtubedl
    image: bitnami/git:latest
    working_dir: /temp
    command: >
      bash -c "
        find /temp -mindepth 1 -delete && 
        git clone https://github.com/Securitybits-io/homelab.git &&
        cp -R ./homelab/apps/youtubedl/* /docker/conf/ 
      "
    volumes:
      - /docker:/docker

  tactube:
    image: securitybits/ytdl
    container_name: ytdl-tactube
    volumes:
      - /docker/conf/tactube:/config
      - /docker/mnt/Tactube:/ytdl
    restart: unless-stopped
    depends_on:
      - git-checkout
  
  youtube:
    image: securitybits/ytdl
    container_name: ytdl-youtube
    volumes:
      - /docker/conf/youtube:/config
      - /docker/mnt/Youtube:/ytdl
    restart: unless-stopped
    depends_on:
      - git-checkout