services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/backup/radarr:/backups
      - /docker/conf/radarr/data:/config
      - /docker/mnt/Movies:/movies 
      - /docker/mnt/downloads/complete:/downloads/complete
    ports:
      - 7878:7878
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/backup/sonarr:/backups
      - /docker/conf/sonarr/data:/config
      - /docker/mnt/Series:/tv 
      - /docker/mnt/downloads/complete:/downloads/complete
    ports:
      - 8989:8989
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/backup/bazarr:/backups
      - /docker/conf/bazarr:/config
      - /docker/mnt/Movies:/movies
      - /docker/mnt/Series:/tv
    ports:
      - 6767:6767
    restart: unless-stopped

  transmission:
    image: linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=${MEDIA_TRANSMISSION_USERNAME}
      - PASS=${MEDIA_TRANSMISSION_PASSWORD}
      - PREALLOCATION=1
      - RATIO_LIMIT=0
      - RATIO_LIMIT_ENABLED=true
    volumes:
      - /docker/conf/transmission:/config
      - /docker/mnt/downloads:/downloads
      - /docker/conf/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/backup/readarr:/backup
      - /docker/conf/readarr/data:/config
      - /docker/mnt/Books:/books 
      - /docker/mnt/downloads/complete:/downloads/complete
    ports:
      - 8787:8787
    restart: unless-stopped
    
  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/conf/prowlarr/config:/config
      - /docker/backup/prowlarr:/backup
    ports:
      - 9696:9696
    restart: unless-stopped

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/conf/tautulli/config:/config
      - /docker/backup/tautulli:/config/backups
    ports:
      - 8181:8181
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr