services:
  # radarr:
  #   image: linuxserver/radarr:latest
  #   container_name: radarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Stockholm
  #   volumes:
  #     - /docker/backup/radarr:/backups
  #     - /docker/conf/radarr/data:/config
  #     - /docker/mnt/Movies:/movies 
  #     - /docker/mnt/downloads/complete:/downloads/complete
  #   ports:
  #     - 7878:7878
  #   restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/backup/sonarr:/backups
      - /docker/conf/sonarr/data:/config
      - /docker/mnt/Series:/tv 
      - /docker/mnt/downloads/complete:/downloads/complete
    ports:
      - 8989:8989
    restart: unless-stopped

  # bazarr:
  #   image: linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Stockholm
  #   volumes:
  #     - /docker/backup/bazarr:/backups
  #     - /docker/conf/bazarr:/config
  #     - /docker/mnt/Movies:/movies
  #     - /docker/mnt/Series:/tv
  #   ports:
  #     - 6767:6767
  #   restart: unless-stopped

  # transmission-openvpn:
  #   image: haugene/transmission-openvpn
  #   container_name: transmission-openvpn
  #   ports:
  #     - '9091:9091'
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - /docker/conf/transmission-openvpn:/data
  #     - /docker/mnt/downloads:/downloads
  #     - /docker/conf/openvpn/:/etc/openvpn/custom/
  #   environment:
  #     - TZ=Europe/Stockholm
  #     - OPENVPN_PROVIDER=custom
  #     - OPENVPN_CONFIG=airvpn
  #     - OPENVPN_USERNAME=${OPENVPN_USER}
  #     - OPENVPN_PASSWORD=${OPENVPN_PASS}
  #     - LOCAL_NETWORK=10.0.0.0/16
  #     - TRANSMISSION_WEB_UI=flood-for-transmission
  #     - TRANSMISSION_PREALLOCATION=1
  #     - TRANSMISSION_RATIO_LIMIT=0
  #     - TRANSMISSION_RATIO_LIMIT_ENABLED=True
  #     - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=200
  #     - TRANSMISSION_DOWNLOAD_DIR=/downloads/complete
  #     - TRANSMISSION_INCOMPLETE_DIR=/downloads/incomplete
  #   restart: unless-stopped

  # nzbgetvpn:
  #   image: jshridha/docker-nzbgetvpn:latest
  #   container_name: nzbgetvpn
  #   ports:
  #     - '6789:6789'
  #   cap_add:
  #     - NET_ADMIN
  #   volumes:
  #     - /docker/conf/openvpn/:/config/openvpn/
  #     - /docker/conf/nzbgetvpn:/config
  #     - /docker/mnt/downloads:/downloads
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - VPN_ENABLED=yes
  #     - VPN_PROV=airvpn
  #     - VPN_CLIENT=openvpn
  #     - ENABLE_PRIVOXY=yes
  #     - LAN_NETWORK=10.0.0.0/16
  #     - NAME_SERVERS=209.222.18.222,84.200.69.80,37.235.1.174,1.1.1.1,209.222.18.218,37.235.1.177,84.200.70.40,1.0.0.1
  #     - ADDITIONAL_PORTS=1234
  #     - DEBUG=false
  #     - UMASK=000
        
  readarr:
    image: linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/backup/readarr:/backup
      - /docker/conf/readarr/data:/config
      - /docker/mnt/Books:/books 
      - /docker/mnt/downloads/complete:/downloads/complete
    ports:
      - 8787:8787
    restart: unless-stopped
    
  # prowlarr:
  #   image: linuxserver/prowlarr:develop
  #   container_name: prowlarr
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/Stockholm
  #   volumes:
  #     - /docker/conf/prowlarr/config:/config
  #     - /docker/backup/prowlarr:/backup
  #   ports:
  #     - 9696:9696
  #   restart: unless-stopped

  tautulli:
    container_name: tautulli
    image: linuxserver/tautulli:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /docker/conf/tautulli/config:/config
      - /docker/backup/tautulli:/config/backups
    ports:
      - 8181:8181
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr
  
  # ombi:
  #   image: linuxserver/ombi:latest
  #   container_name: ombi
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Europe/London
  #   volumes:
  #     - /docker/conf/ombi/config:/config
  #   ports:
  #     - 3579:3579
  #   restart: unless-stopped
  #   security_opt: # Temp Fix
  #     - seccomp=unconfined