{
 "title": "Proxmox",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Proxmox - Cpu Usage (VM / %)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pve_cpu_usage_ratio * on(id) group_left(name) (pve_guest_info)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxmox - Memory Usage (VM / Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pve_memory_usage_bytes * on(id) group_left(name) (pve_guest_info)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Proxmox VM - Network Tx/Rx (Bytes/Sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_network_receive_bytes[5m]) * on(id) group_left(name) (pve_guest_info)",
     "legendFormat": "{{name}} - Rx"
    },
    {
     "expr": "rate(pve_network_transmit_bytes[5m]) * on(id) group_left(name) pve_guest_info * -1",
     "legendFormat": "{{name}} - Tx"
    }
   ]
  },
  {
   "title": "Proxmox VM - Disk IO (Bytes/Sec)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pve_disk_read_bytes[5m]) * on(id) group_left(name) (pve_guest_info)",
     "legendFormat": "{{name}} - Read"
    },
    {
     "expr": "rate(pve_disk_write_bytes[5m]) * on(id) group_left(name) pve_guest_info * -1",
     "legendFormat": "{{name}} - Write"
    }
   ]
  }
 ]
}