{
 "title": "System Logs",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Log sources",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (rate({instance=~\".+\"} |= `` [$__auto]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Histogram",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(level) (rate({level=~\".+\"} |= `` [$__auto]))",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 34, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{instance=~\".+\"} |= ``"
    }
   ]
  }
 ]
}