---
- name: Add consul Server Configuration File
  template:
    src: "files/consul.hcl.j2"
    dest: "/etc/consul.d/consul.hcl"
    owner: consul
  tags:
    - install-consul
    - configure

- name: Restart consul
  ansible.builtin.service:
    name: consul
    state: restarted
  tags:
    - install-consul
    - configure
    - restart