{
 "title": "Homepage",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "PFSense" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "Bifrost.securitybits.local" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "QNAP_Nidhoggr",
     "select": [
      [
       { "params": [ "SystemUptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "QNAP" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UniFi_Core",
     "select": [
      [
       { "params": [ "SystemUptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unifi Core" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "UniFi_NanoHD_Office",
     "select": [
      [
       { "params": [ "SystemUptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Unifi NanoHD" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 12, "w": 14, "x": 6, "y": 0 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "query": "SELECT percent_packet_loss AS \"metric\" FROM \"ping\" WHERE (\"geohash\" != '') AND time > now() - 2m GROUP BY \"geohash\", \"url\" LIMIT 1\n",
     "select": [
      [
       { "params": [ "percent_packet_loss" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "geohash", "operator": "!=", "value": "''" }
     ]
    }
   ]
  },
  {
   "title": "VM Memory Used",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "alias": "$tag_vmname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_mem",
     "query": "SELECT last(\"usage_average\") FROM \"vsphere_vm_cpu\" AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "path", "operator": "=", "value": "/" },
      { "condition": "OR", "key": "path", "operator": "=", "value": "/var/run" }
     ]
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "watts" }
     ]
    }
   ]
  },
  {
   "title": "VM CPU Load",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "targets": [
    {
     "alias": "$tag_vmname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "vmname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsphere_vm_cpu",
     "query": "SELECT last(\"usage_average\") FROM \"vsphere_vm_cpu\" AND $timeFilter GROUP BY time($__interval) fill(null)\n",
     "select": [
      [
       { "params": [ "usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Host CPU Temp",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "unit", "operator": "=", "value": "degrees_c" }
     ]
    }
   ]
  },
  {
   "title": "Speedtest",
   "type": "graph",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "yaxes": [
    { "format": "bps", "label": "Speed" }
   ],
   "targets": [
    {
     "alias": "Download",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "download",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "Upload",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "upload",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Ping Rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Plex",
   "type": "text",
   "gridPos": { "h": 1, "w": 20, "x": 0, "y": 17 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Ombi",
   "type": "text",
   "gridPos": { "h": 1, "w": 4, "x": 20, "y": 17 },
   "options": {
    "content": "# Title\n\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)\n         "
   },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "LAN Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT mean(\"value\") FROM \"Tautulli\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "lan_bandwidth" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT last(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =\"Movies\") AND $timeFilter\n",
     "select": [
      [
       { "params": [ "stream_count" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT last(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =\"Movies\") AND $timeFilter\n",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "Movies" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Radarr",
     "query": "SELECT last(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =\"Movies\") AND $timeFilter\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "Missing_Available", "operator": "=", "value": "0" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "pending" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT last(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =\"Movies\") AND $timeFilter\n",
     "select": [
      [
       { "params": [ "direct_play_streams" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "WAN Bandwidth",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT mean(\"value\") FROM \"Tautulli\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "wan_bandwidth" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT last(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =\"Movies\") AND $timeFilter\n",
     "select": [
      [
       { "params": [ "total" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "library_stats" },
      { "condition": "AND", "key": "section_name", "operator": "=", "value": "TV Shows" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Sonarr",
     "query": "SELECT last(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =\"Movies\") AND $timeFilter\n",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Missing" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Ombi",
     "select": [
      [
       { "params": [ "available" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Request_Counts" }
     ]
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Tautulli",
     "query": "SELECT last(\"total\") FROM \"Tautulli\" WHERE (\"type\" = 'library_stats' AND \"section_name\" =\"Movies\") AND $timeFilter\n",
     "select": [
      [
       { "params": [ "transcode_streams" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "longitude" ], "type": "tag" },
      { "params": [ "latitude" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       },
       { "params": [ "metric" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Stream Types",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_video_decision",
     "groupBy": [
      { "params": [ "1w" ], "type": "time" },
      { "params": [ "video_decision" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Users",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 24 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "alias": "$tag_username",
     "groupBy": [
      { "params": [ "username" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  },
  {
   "title": "Online Users",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "title" ], "type": "tag" },
      { "params": [ "friendly_name" ], "type": "tag" },
      { "params": [ "quality" ], "type": "tag" },
      { "params": [ "device_type" ], "type": "tag" },
      { "params": [ "player_state" ], "type": "tag" },
      { "params": [ "video_decision" ], "type": "tag" },
      { "params": [ "full_location" ], "type": "tag" }
     ],
     "measurement": "Tautulli",
     "query": "SELECT distinct(\"hash\") FROM \"Tautulli\" WHERE (\"type\" = 'Session') AND $timeFilter GROUP BY \"title\", \"friendly_name\", \"quality\", \"video_decision\", \"quality_profile\", \"platform\", \"product_version\", \"full_location\", \"username\", \"player_state\"",
     "select": [
      [
       { "params": [ "hash" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "type", "operator": "=", "value": "Session" }
     ]
    }
   ]
  }
 ]
}