---
# tasks file for ytdl
  - name: Only run "update_cache=yes" if the last one is more than 36000 seconds ago
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 36000
    become: True

  - name: install yt-dlp dependencies
    apt:
      name: '{{ ytdl_dependencies }}'
      state: present

  - name: install yt-dlp
    pip:
      name: yt-dlp
      state: present

  - name: create channel file
    template:
      src: channel.list
      dest: "/opt/channel.list"

  - name: create ytdl shellscript
    copy:
      dest: /opt/youtube-dl.sh
      mode: "0744"
      content: |
        #!/bin/bash
        /usr/local/bin/yt-dlp {{ item }}
    with_items: '{{ opts }}'

  - name: create cronjob for /opt/youtube-dl
    cron:
      name: SECBITS_YOUTUBE_DOWNLOAD
      job: /usr/bin/sh /opt/youtube-dl.sh
      minute: "2"
      hour: "0"
