version: "3.8"

services:
  maptilesdownloader:
    container_name: maptilesdownloader
    image: aliashraf/map-tiles-downloader
    ports:
      - 8081:8080
    volumes:
      - /docker/data/maptilesdownloader/output:/app/output/
    restart: always