services:
  mysqlpiwigo:
    image: mariadb:latest
    container_name: piwigo-reference-mariadb
    volumes:
        - /docker/conf/piwigo/mysql/:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_PIWIGO_ROOT_PASSWORD}
        - MYSQL_DATABASE=piwigo
        - MYSQL_USER=piwigo
        - MYSQL_PASSWORD=${MYSQL_PIWIGO_PASSWORD}
  piwigo:
    image: lscr.io/linuxserver/piwigo:latest
    container_name: piwigo-reference-gallery
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /docker/conf/piwigo-reference:/config
      - /docker/data/piwigo-reference:/gallery
    ports:
      - 80:80
    restart: unless-stopped