job "sidecar-countdash" {
  datacenters = ["*"]

  group "api" {
    network {
      mode = "bridge"
      port "api" { to = 9001 }
    }
    
    service {
      name = "count-api"
      port = "9001"

      connect {
        sidecar_service {
          proxy {
            expose {
              path {
                path = "/"
                protocol = "http"
                local_path_port = 9001
                listener_port = "api"
              }
            }
          }
        }
      }

      tags = [
        "traefik.enable=true",
        "traefik.http.routers.countdash.service=count-api",
        "traefik.http.routers.countdash.rule=Host(`count.securitybits.io`)",
        "traefik.http.routers.countdash.entrypoints=websecure",
        "traefik.http.routers.countdash.tls.certresolver=letsencrypt"
      ]
    }

    task "web" {
      driver = "docker"

      config {
        image = "hashicorpdev/counter-api:v3"
      }
    }
  }
}