---
- hosts: elastic_breachsearch_kibana
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - elasticsearch
    - kibana

  tasks: 
    - name: Configure elasticsearch
      copy:
        dest: /etc/elasticsearch/elasticsearch.yml
        content: |
          cluster.name: breachsearch
          node.name: ${HOSTNAME}
          node.roles:
            - master
          node.attr.rack: husqvarna
          node.attr.box_type: master
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          discovery.seed_hosts: 
            - elastic-breachsearch-kibana-01
          network.host: 0.0.0.0
          http.port: 9200
          xpack.security.enabled: false
          xpack.security.transport.ssl.enabled: false
          xpack.security.http.ssl.enabled: false
      notify: restart elasticsearch

    - name: Configure kibana
      copy:
        dest: /etc/kibana/kibana.yml
        content: |
          server.port: 5601
          server.host: 0.0.0.0
          server.name: "Breachsearch Kibana"
          server.ssl.enabled: false
          elasticsearch.hosts: ["http://localhost:9200"]
          #logging.root.level: debug
          logging:
            appenders:
              file:
                type: file
                fileName: /var/log/kibana/kibana.log
                layout:
                  type: json
            root:
              appenders:
                - default
                - file
          #  layout:
          #    type: json
          pid.file: /run/kibana/kibana.pid
      notify: restart kibana

