---
- hosts: elastic_breachsearch
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - elasticsearch

  tasks: 
    - name: Configure elasticsearch
      copy:
        dest: /etc/elasticsearch/elasticsearch.yml
        content: |
          cluster.name: breachsearch
          node.name: ${HOSTNAME}
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          discovery.seed_hosts: ["elastic-breachsearch-hot-01", "elastic-breachsearch-hot-02"]
          network.host: 0.0.0.0
          xpack.security.enabled: false
          xpack.security.transport.ssl.enabled: false
          xpack.security.http.ssl.enabled: false
      notify: restart elasticsearch