---
- hosts: elastic_breachsearch
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - elasticsearch

  tasks: 
    - name: Configure elasticsearch
      copy:
        dest: /etc/elasticsearch/elasticsearch.yml
        content: |
          cluster.name: breachsearch
          node.name: ${HOSTNAME}
          node.master: false
          node.data: True
          node.attr.rack: husqvarna
          node.attr.box_type: hot
          path.data: /var/lib/elasticsearch
          path.logs: /var/log/elasticsearch
          discovery.seed_hosts: 
            - elastic-breachsearch-hot-01
            - elastic-breachsearch-hot-02
            - elastic-breachsearch-hot-03
          cluster.initial_master_nodes:
            - elastic-breachsearch-kibana-01
          network.host: 0.0.0.0
          http.port: 9200
          xpack.security.enabled: false
          xpack.security.transport.ssl.enabled: false
          xpack.security.http.ssl.enabled: false
      notify: restart elasticsearch