---
- hosts: nomad_servers
  gather_facts: yes
  become: yes
  vars:
    nomad_type: server
    consul_type: client
    use_consul: true
  roles:
    - common
    - cis
    - ssh
    - consul
    - docker
    - nomad
    - nomad_cni_plugins
  tasks:
    - name: Copy folder to /opt/jobs
      ansible.builtin.copy:
        src: ../jobs  # Local folder on the Ansible controller
        dest: /opt    # Target directory on the node
        owner: root
        group: root
        mode: '0755'
      tags:
        jobs
    
    - name: Push nomad variables and secrets
      tags:
        - jobs
        - secrets
      block:
        - name: Find all job-var files
          find:
            paths: host_vars/nomad/jobs-vars
            patterns: "*.nv.hcl"
          delegate_to: localhost
          register: job_var_files

        - name: Create /opt/jobs-vars
          file:
            path: /opt/jobs-vars
            state: directory
            owner: root
            group: root
            mode: "0600"

        - name: Copy job-var files to remote host
          copy:
            src: "{{ item.path }}"
            dest: "/opt/jobs-vars/{{ item.path | basename }}"
            mode: "0700"
          with_items: "{{ job_var_files.files }}"
          register: changed_files

        - name: Apply Nomad var from files
          command: nomad var put -force @/opt/jobs-vars/{{ item.path | basename }}
          with_items: "{{ changed_files.results }}"
          when: item.changed


- hosts: nomad_clients
  gather_facts: yes
  become: yes
  vars:
    nomad_type: client  # Nomad server/client
    consul_type: client # Consul server/client
    use_consul: true
  roles:
    - common
    - cis
    - ssh
    - consul
    - docker
    - nomad
    - nomad_cni_plugins
