---
- hosts: offsec-docker-01
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - docker

  tasks:
    - name: create /opt/offsec
      file:
        path: /opt/offsec
        state: folder
        mode: "0755"

    - name: copy docker-compose to /opt
      copy:
        src: "../apps/offsec/{{ item }}"
        dest: "/opt/offsec/{{ item }}"
      loop:
        - docker-compose.yml

    - name: docker compose up
      community.docker.docker_compose:
        project_src: /opt/offsec
        files:
          - docker-compose.yml