---
- hosts: private-ytdl
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - smb-mount
    - ytdl

    
  tasks:
    - name: install yt-dlp stash
      pip:
        name: 
          - stashapp-tools
          - https://github.com/schmoaaaaah/yt-dlp-stash/archive/master.zip