---
- hosts: public-docker-01
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - smb-mount
    - docker

  tasks:
    - name: create /opt/immich
      file:
        path: /opt/immich
        state: directory
        mode: "0755"

    - name: Immich copy docker-compose to /opt
      copy:
        src: "../apps/immich"
        dest: "/opt/"

    - name: Immich copy docker env file from secrets
      copy:
        src: "/opt/homelab-secrets/apps/immich/secrets.env"
        dest: "/opt/immich/.env"

    - name: Immich docker-compose pull
      community.docker.docker_compose:
        project_src: /opt/immich
        pull: true
        files:
          - docker-compose.yml

    - name: Immich docker-compose up
      community.docker.docker_compose:
        project_src: /opt/immich
        files:
          - docker-compose.yml

    - name: create /opt/microbin
      file:
        path: /opt/microbin
        state: directory
        mode: "0755"

    - name: microbin copy docker-compose to /opt
      copy:
        src: "../apps/microbin"
        dest: "/opt/"

    - name: microbin docker-compose pull
      community.docker.docker_compose:
        project_src: /opt/microbin
        pull: true
        files:
          - docker-compose.yml

    - name: microbin docker-compose up
      community.docker.docker_compose:
        project_src: /opt/microbin
        files:
          - docker-compose.yml