--- 
- import_playbook: ansible.yml
- import_playbook: mgmt-docker-01.yml
- import_playbook: logging-docker-01.yml
- import_playbook: offsec-docker-01.yml
- import_playbook: public-docker-01.yml
- import_playbook: atak-docker-01.yml
- import_playbook: media-docker-01.yml
- import_playbook: plex.yml
- import_playbook: nginx.yml
- import_playbook: ytdl-tactube.yml
- import_playbook: ytdl-youtube.yml
- import_playbook: private-ytdl.yml