version: '3'
services:
  actual_server:
    container_name: actual
    image: docker.io/actualbudget/actual-server:latest
    ports:
      - 5006:5006
    volumes:
      - /docker/data/actual-data:/data
    restart: unless-stopped