job "sidecar-ubuntu" {
  datacenters = ["*"]

  group "ubuntu" {
    network {
      mode = "bridge"
    }

    service {
      name = "sidecar-ubuntu"
      provider = "consul"

			connect {
       sidecar_service {
          proxy {
            upstreams {
              destination_name = "count-api"
              local_bind_port = 8080
            }
          }
        }
      }
    }

    task "ubuntu-task" {
      driver = "docker"

      config {
        image = "ubuntu:latest"
        tty   = true
        args  = ["sleep", "infinity"]
      }

      resources {
        cpu    = 500   # 500 MHz
        memory = 256   # 256MB RAM
      }
    }
  }
}
