job "whoami-1" {
  datacenters = ["*"]
  
  type = "service"

  group "demo" {
    count = 1

    network {
      mode = "bridge"
      port "http" {
        to = 8081
      }
    }

    service {
      name = "whoami-1-demo"
      port = "http"
      provider = "consul"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name  = "whoami-2-demo"
              local_bind_port   = 8082
            }
          }
        }
      }
    }

    task "server" {
      env {
        WHOAMI_PORT_NUMBER = "${NOMAD_PORT_http}"
      }

      driver = "docker"

      config {
        image = "traefik/whoami"
        ports = ["http"]
      }
    }
  }
}