job "microbin-sidecar" {
  datacenters = ["*"]
  
  type = "service"

  group "microbin-sidecar" {
    network {
      mode = "bridge"
      port "http" {
        to = 8080
      }
    }

    service {
      name = "microbin-sidecar"
      port = "http"
      provider = "consul"

      connect {
        sidecar_service {
          proxy {
            upstreams {
              destination_name  = "whoami-2-demo"
              local_bind_port   = 8082
            }
          }
        }
      }
    }

    task "microbin-sidecar" {
      driver = "docker"
      config {
        image = "danielszabo99/microbin"
        ports = ["http"]
      }
    }
  }
}