job "whoami-2" {
  datacenters = ["*"]
  
  type = "service"

  group "demo" {
    count = 1

    network {
       port "http" {
         to = 8082
       }
    }

    service {
      name = "whoami-2-demo"
      port = "http"
      provider = "consul"

      connect {
        sidecar_service {}
      }
    }

    task "server" {
      env {
        WHOAMI_PORT_NUMBER = "${NOMAD_PORT_http}"
      }

      driver = "docker"

      config {
        image = "traefik/whoami"
        ports = ["http"]
      }
    }
  }
}