---
  - hosts: 
      - docker_hosts
      - nomad_clients
    become: yes
    gather_facts: no

    tasks:
    - name: docker container ls -a
      tags: container_ls
      become: True
      shell:
        "docker container ls -a"
      register: container_info

    - name: docker container ls -a result
      tags: container_ls
      debug:
        msg: "{{container_info.stdout_lines}}"