---
- name: Gather Vault repository facts
  ansible.builtin.setup:
    gather_subset:
      - '!all'
      - min
  tags:
    - install-vault

- name: Install required system packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - wget
      - coreutils
      - gpg
    state: present
    update_cache: true
    lock_timeout: 180
  tags:
    - install-vault

- name: Ensure apt keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  tags:
    - install-vault

- name: Get Hashicorp GPG key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp-archive-keyring.asc
    mode: '0644'
    force: true
  tags:
    - install-vault
    - get-gpg-key

- name: Remove legacy Hashicorp vault repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com jammy main"
    state: absent
    update_cache: false
  tags:
    - install-vault
    - update-repository

- name: Add Hashicorp vault repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
    state: present
    update_cache: false
  tags:
    - install-vault
    - update-repository

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    force_apt_get: true
  tags:
    - install-vault
    - update

- name: Install Vault packages
  ansible.builtin.apt:
    name: vault
    state: present
    lock_timeout: 180
  tags:
    - install-vault
    - install-package
