---
# tasks file for docker
  - name: Install required system packages
    apt:
      pkg:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - virtualenv
        - python3-pip
        - python3-setuptools
      state: latest
      update_cache: true
      lock_timeout: 180

  - name: Add Docker GPG apt Key
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/trusted.gpg.d/docker.asc

  - name: Add Docker Repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu jammy stable
      state: present

  - name: Update apt and install docker-ce
    apt:
      name: docker-ce
      state: latest
      update_cache: true

  - name: Install Docker Module for Python
    apt:
      pkg: 
        - python3-docker

  # - name: Install Docker-Compose Module for Python
  #   apt:
  #     pkg: 
  #       - python3-compose