---
- hosts: atak-docker-01
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - alloy
    - docker

  tasks:
    - name: create /opt/atak
      file:
        path: /opt/atak
        state: directory
        mode: "0755"

    - name: ATAK copy docker-compose to /opt
      copy:
        src: "../apps/atak"
        dest: "/opt/"

    - name: ATAK copy docker env file from secrets
      copy:
        src: "/opt/homelab-secrets/apps/atak/secrets.env"
        dest: "/opt/atak/.env"

    - name: ATAK docker-compose pull
      community.docker.docker_compose:
        project_src: /opt/atak
        pull: true
        files:
          - docker-compose.yml

    - name: ATAK docker-compose up
      community.docker.docker_compose:
        project_src: /opt/atak
        files:
          - docker-compose.yml

    # MQTT Setup
    - name: Create /opt/meshtastic
      file:
        path: /opt/meshtastic
        state: directory
        mode: "0755"

    - name: MQTT copy files to /opt
      copy:
        src: "../apps/meshtastic"
        dest: "/opt/"
    
    - name: MQTT copy pwfile file from secrets
      copy:
        src: "/opt/homelab-secrets/apps/meshtastic/pwfile"
        dest: "/opt/meshtastic/config/pwfile"