---
- hosts: offsec-docker-01
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - docker

  tasks:
    - name: create /opt/offsec
      file:
        path: /opt/offsec
        state: directory
        mode: "0755"

    - name: copy docker-compose to /opt
      copy:
        src: "../apps/offsec"
        dest: "/opt/"

    - name: docker-compose pull
      community.docker.docker_compose_v2:
        project_src: /opt/offsec
        pull: "always"
        files:
          - docker-compose.yml


    - name: docker-compose up
      community.docker.docker_compose_v2:
        project_src: /opt/offsec
        files:
          - docker-compose.yml