---
- hosts: takserver
  become: True
  gather_facts: no
  
  roles:
    - common
    - cis
    - ssh
    - alloy
    - smb-mount
    - docker

  tasks:
    - name: Install dependencies
      apt:
        name:
          - net-tools
          - zip
          - unzip
          - openjdk-11-jre-headless
        state: present
        update_cache: True

    - name: create /opt/takserver
      file:
        path: /opt/takserver
        state: directory
        mode: "0755"

    - name: Clone Cloud-RF TAKServer
      git:
        repo: https://github.com/Cloud-RF/tak-server.git
        dest: /opt/takserver
      become: True

    - name: Copy TAKServer 4.9 to /opt/takserver
      copy:
        remote_src: True
        src: "/tak/TAK-Software/TAKServer/4.9.0/takserver-docker-4.9-RELEASE-23.zip"
        dest: "/opt/takserver/takserver-docker-4.9-RELEASE-23.zip"

    # - name: Copy TAKServer 4.8 to /opt/takserver
    #   copy:
    #     remote_src: True
    #     src: "/tak/TAK-Software/TAKServer/4.8.0/takserver-docker-4.8-RELEASE-31.zip"
    #     dest: "/opt/takserver/takserver-docker-4.8-RELEASE-31.zip"
