---
# roles/grafana_alloy/tasks/configure.yml

- name: Create alloy user
  ansible.builtin.user:
    name: alloy
    system: yes
    shell: /bin/false
    create_home: no
  tags: 
    - install-alloy

- name: Add alloy to docker group
  ansible.builtin.user:
    name: alloy
    state: present
    groups: docker
    append: yes
  tags: 
    - install-alloy
  when: "'docker_hosts' in group_names or 'nomad_clients' in group_names"

- name: Create Alloy config and data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: alloy
    group: alloy
    mode: '0750'
  loop:
    - "{{ alloy_config_dir }}"
    - "{{ alloy_data_dir }}"
  tags: 
    - install-alloy
    

- name: Template Alloy configuration file
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "{{ alloy_config_dir }}/config.alloy"
    owner: alloy
    group: alloy
    mode: '0640'
  notify: Restart alloy
  tags: 
    - install-alloy
    - configure
    

- name: Ensure alloy service is enabled and started
  ansible.builtin.systemd:
    name: alloy
    state: started
    enabled: yes
    daemon_reload: yes
  tags: 
    - install-alloy
    - configure
    