---
# tasks file for smb-mount
  - name: Only run "update_cache=yes" if the last one is more than 36000 seconds ago
    ansible.builtin.apt:
      update_cache: yes
      cache_valid_time: 36000
    become: True

  - name: Install mount Dependencies
    apt:
      name: "{{ smb_dependencies }}"
      state: present

  - name: Mount folders
    mount:
      src: '{{ item.src }}'
      path: '{{ item.path }}'
      opts: '{{ item.opts }}'
      fstype: '{{ item.type }}'
      state: mounted
    with_items: '{{ mounts }}'