---
- hosts: docker
  tasks:
  - name: Run portainer-agent
    docker_container:
      name: portainer-agent
      image: portainer/agent:latest
      state: started
      ports:
        - "9001:9001"
      restart: yes
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
        - "/var/lib/docker/volumes:/var/lib/docker/volumes"